[package]
name = "tnet"
version = "0.1.0"
edition = "2021"

[lib]
name = "tnet"
path = "src/lib.rs"

[features]
default = ["server", "transaction"]
server = ["transaction"]
client = ["transaction"]
async = ["transaction"]
transaction = []

[dependencies]
tnet_proc_macros = { path = "tnet_proc_macros" }
serde = { version = "1.0.215", features = ["derive"] }
colored = "2.1.0"
bincode = "1.3.3"
uuid = { version = "1.11.0", features = ["v4"] }
tlogger = { path = "../t-logger" }
tokio = { version = "1.41.1", features = ["full"] }
