[package]
name = "tnet-macros"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
ctor = "0.4.1"
once_cell = "1.21.1"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
